DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "Concepts" CASCADE;
DROP TABLE IF EXISTS "Properties" CASCADE;
DROP TABLE IF EXISTS "EntityProperties" CASCADE;
DROP TABLE IF EXISTS "Entities";
DROP TABLE IF EXISTS "Indicators" CASCADE;
DROP TABLE IF EXISTS "DataPoints" CASCADE;
DROP TABLE IF EXISTS "Dimentions" CASCADE;
DROP TABLE IF EXISTS "DataPointDimention";

CREATE TABLE "Users" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "email" VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "Concepts" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "type" VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "UserId" INTEGER NOT NULL,
  FOREIGN KEY ("UserId") REFERENCES "Users"("id") ON UPDATE CASCADE
);

CREATE TABLE "Properties" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "type" VARCHAR(255) NOT NULL,
  "info" VARCHAR(255) NOT NULL,
  "date" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "EntityProperties" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "name" VARCHAR(255) NOT NULL,
  "type" VARCHAR(255),
  "info" VARCHAR(255),
  "date" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE "Entities" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "name" VARCHAR(255),
  "ConceptId" INTEGER NOT NULL,
  "EntityPropertyId" INTEGER NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY ("ConceptId") REFERENCES "Concepts"("id") ON UPDATE CASCADE,
  FOREIGN KEY ("EntityPropertyId") REFERENCES "EntityProperties"("id") ON UPDATE CASCADE

);

CREATE TABLE "Indicators" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "value" VARCHAR(255) NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "PropertyId" INTEGER NOT NULL,
  "ConceptId" INTEGER NOT NULL,
  FOREIGN KEY ("PropertyId") REFERENCES "Properties"("id") ON UPDATE CASCADE,
  FOREIGN KEY ("ConceptId") REFERENCES "Concepts"("id") ON UPDATE CASCADE
);

CREATE TABLE "DataPoints" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "UserId" INTEGER NOT NULL,
  "IndicatorId" INTEGER NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY ("UserId") REFERENCES "Users"("id") ON UPDATE CASCADE,
  FOREIGN KEY ("IndicatorId") REFERENCES "Indicators"("id") ON UPDATE CASCADE
);

CREATE TABLE "Dimentions" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "key" VARCHAR(255) NOT NULL,
  "PropertyId" INTEGER NOT NULL,
  "ConceptId" INTEGER NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY ("PropertyId") REFERENCES "Properties"("id") ON UPDATE CASCADE,
  FOREIGN KEY ("ConceptId") REFERENCES "Concepts"("id") ON UPDATE CASCADE
);

CREATE TABLE "DataPointDimention" (
  "DataPointId" INTEGER NOT NULL,
  "DimentionId" INTEGER NOT NULL,
  PRIMARY KEY ("DataPointId", "DimentionId"),
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  FOREIGN KEY ("DataPointId") REFERENCES "DataPoints"("id") ON UPDATE CASCADE,
  FOREIGN KEY ("DimentionId") REFERENCES "Dimentions"("id") ON UPDATE CASCADE
);
